# Site settings
title: "namespace acoustikue"
title_show: "namespace acoustikue"
url: "https://sjoon-oh.github.io"
baseurl: "" 
description: >
  An engineer dreamer.

# modded by acoustikue
email: sjoon.oh@pm.me # modded by acoustikue
author: SukJoon Oh
avatar: "/assets/profile-3.jpg"
profile: An engineer dreamer.
#twitter_username: twitter_username
#github_username:  

# added by acoustikue
logo: "/assets/logo_mod.png"

profile_links:
  Email: "mailto:sjoon.oh@pm.me"
  GitHub: "https://github.com/sjoon-oh"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus)
#  choose one and un-comment the line to active it
disqus_shortname: acoustikue   # get one: https://disqus.com/admin/signup/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    CV: /assets/cv_sukjoon_oh.pdf
    Archiver: /archivers/
    # modded by acoustikue

#permalink: /archivers/:title # modded by acoustikue
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
