# Site settings
title: "namespace acoustikue"
title_show: "namespace acoustikue { }"
url: "https://dev-acoustikue.github.io"
baseurl: "" 
description: >
  An experience-hungry engineer dreamer.

# modded by acoustikue
email: acoustikue@yonsei.ac.kr # modded by acoustikue
author: acoustikue
avatar: "/assets/profile_mod.png"
profile: An experience-hungry engineer dreamer.
#twitter_username: twitter_username
#github_username:  dev-acoustikue

# added by acoustikue
logo: "/assets/logo_mod.png"

profile_links:
  Email: "mailto:acoustikue@yonsei.ac.kr"
  GitHub: "https://github.com/dev-acoustikue"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus)
#  choose one and un-comment the line to active it
disqus_shortname: acoustikue   # get one: https://disqus.com/admin/signup/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Archiver: /archivers/
    # modded by acoustikue

#permalink: /archivers/:title # modded by acoustikue
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
